theme = "ayu_dark"

[editor]
auto-save = true
shell = ["zsh", "-c"]
bufferline = "multiple"

[editor.statusline]
left =  ["mode", "spinner", "file-base-name", "read-only-indicator", "file-modification-indicator"]
right = ["file-type", "diagnostics", "selections", "register", "position", "file-encoding"]
mode.normal = "[N]"
mode.insert = "[I]"
mode.select = "[V]"

[editor.indent-guides]
render = true
character = "·"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
