theme = "ayu_mirage"

[editor]
auto-save = true
true-color = true
cursorline = true
shell = ["zsh", "-c"]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "·"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

[editor.statusline]
left =  ["mode", "spinner", "file-base-name", "read-only-indicator", "file-modification-indicator"]
center = ["version-control"]
right = ["file-type", "diagnostics", "selections", "register", "position", "file-encoding"]
mode.normal = "[N]"
mode.insert = "[I]"
mode.select = "[V]"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-s = ":w" # Save files with ctrl+s
A-n = ":new" # New buffer
A-q = ":bc!" # Close current buffer
A-right = "goto_next_buffer" # Move to next buffer with ctrl plus right arrow
A-left = "goto_previous_buffer" # Move to previous buffer with ctrl plus right arrow
"tab" = "goto_next_function" # Select and jump to the next function via Treesitter
"S-tab" = "goto_prev_function" # Select and jump to the previous function via Treesitter
